<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!--dotnet publish ./MyProject.csproj /p:Version="1.2.3" /p:InformationalVersion="1.2.3-qa"-->
    <Version>0.0.0.0</Version>
    <FileVersion>0.0.0.0</FileVersion>
    <InformationalVersion>0.0.0.0</InformationalVersion>
  </PropertyGroup>  
  <PropertyGroup>
    <MyTargetFramework>net10.0</MyTargetFramework>
    <!--<MyTargetFramework>net9.0</MyTargetFramework>-->
    <PlatformTarget>AnyCPU</PlatformTarget>
    <!--<Platforms>x64</Platforms>-->
  </PropertyGroup>
  <PropertyGroup Condition="'$(MyTargetFramework)'=='net6.0'">
    <TargetFramework Condition="'$(TargetFrameworkVariation)'==''">net6.0</TargetFramework>
    <TargetFramework Condition="'$(TargetFrameworkVariation)'=='windows'">net6.0-windows</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MyTargetFramework)'=='net8.0'">
    <TargetFramework Condition="'$(TargetFrameworkVariation)'==''">net8.0</TargetFramework>
    <TargetFramework Condition="'$(TargetFrameworkVariation)'=='windows'">net8.0-windows</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MyTargetFramework)'=='net9.0'">
    <TargetFramework Condition="'$(TargetFrameworkVariation)'==''">net9.0</TargetFramework>
    <TargetFramework Condition="'$(TargetFrameworkVariation)'=='windows'">net9.0-windows</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MyTargetFramework)'=='net10.0'">
    <TargetFramework Condition="'$(TargetFrameworkVariation)'==''">net10.0</TargetFramework>
    <TargetFramework Condition="'$(TargetFrameworkVariation)'=='windows'">net10.0-windows</TargetFramework>
  </PropertyGroup>
  <!--for project files-->
  <!--https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort-->
  <!--https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges-->
  <!--https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management-->
  <!--https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files-->
  <!--<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
  </ItemGroup>-->
  <!--<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
  </ItemGroup>-->
</Project>