namespace vSharpStudio.vm.DbModel
{
    public class DatabaseColumn
    {
        public virtual DatabaseTable Table { get; set; }

        /// <summary>
        ///     The column name.
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        ///     Indicates whether or not this column can contain <c>NULL</c> values.
        /// </summary>
        public virtual bool IsNullable { get; set; }

        /// <summary>
        ///     The database/store type of the column.
        /// </summary>
        public virtual string StoreType { get; set; }

        /// <summary>
        ///     The default constraint for the column, or <c>null</c> if none.
        /// </summary>
        public virtual string DefaultValueSql { get; set; }

        /// <summary>
        ///     The SQL expression that computes the value of the column, or <c>null</c> if this is not a computed column.
        /// </summary>
        public virtual string ComputedColumnSql { get; set; }

        /// <summary>
        ///     Indicates when values will be generated by the database for this column, or <c>null</c> if
        ///     the database will not generate values.
        /// </summary>
        public virtual ValueGenerated? ValueGenerated { get; set; }
    }
}
