// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenFromProto
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Clone : CloneBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 6 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (this.Doc.IsDefaultBase) { 
            
            #line default
            #line hidden
            this.Write("public override void Sort(Type type)\r\n{\r\n");
            
            #line 9 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    int isort=0;
      foreach (var field in message.Fields.InDeclarationOrder()) {
        if (field.IsRepeated) { 
          isort++; 
            
            #line default
            #line hidden
            
            #line 13 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (!field.IsAny()) { 
            
            #line default
            #line hidden
            this.Write("    if (type == typeof(");
            
            #line 14 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write("))\r\n    {\r\n        this.");
            
            #line 16 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Sort();\r\n    }\r\n");
            
            #line 18 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            
            #line 19 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      }
      }
      if (isort==0) { 
            
            #line default
            #line hidden
            this.Write("    //throw new Exception();\r\n");
            
            #line 23 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 25 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            this.Write("public static ");
            
            #line 26 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" Clone(");
            
            #line 26 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" from, bool isDeep = true");
            
            #line 26 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (this.Doc.BaseClass.StartsWith(" : ConfigObjectBase")) { 
            
            #line default
            #line hidden
            this.Write(", bool isNewGuid = false");
            
            #line 26 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n    ");
            
            #line 28 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" vm = new ");
            
            #line 28 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 29 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    foreach (var field in message.Fields.InDeclarationOrder()) { 
            
            #line default
            #line hidden
            
            #line 30 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      if (field.IsRepeated) { 
            
            #line default
            #line hidden
            
            #line 31 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (field.IsAny()) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 32 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new ObservableCollection<Google.Protobuf.WellKnownTypes.Any>();\r\n    foreach(v" +
                    "ar t in from.");
            
            #line 33 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n        vm.");
            
            #line 34 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(t.Clone());\r\n");
            
            #line 35 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else if (!field.IsMessage()) { 
            
            #line default
            #line hidden
            this.Write("    foreach(var t in from.");
            
            #line 36 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n        vm.");
            
            #line 37 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(t);\r\n");
            
            #line 38 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else if (!JsonDoc.Files[root.Name].Messages[field.MessageType.Name].IsDefaultBase) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 39 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new ObservableCollection<");
            
            #line 39 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(">();\r\n    foreach(var t in from.");
            
            #line 40 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n        vm.");
            
            #line 41 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(vSharpStudio.vm.ViewModels.");
            
            #line 41 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".Clone((");
            
            #line 41 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")t, isDeep));\r\n");
            
            #line 42 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 43 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new SortedObservableCollection<");
            
            #line 43 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(">();\r\n    foreach(var t in from.");
            
            #line 44 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n        vm.");
            
            #line 45 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(vSharpStudio.vm.ViewModels.");
            
            #line 45 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".Clone((");
            
            #line 45 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")t, isDeep));\r\n");
            
            #line 46 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            
            #line 47 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name == "string_nullable") { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 48 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 48 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 49 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name.EndsWith("_nullable")) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 50 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 50 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue ? from.");
            
            #line 50 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value : (");
            
            #line 50 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")null;\r\n");
            
            #line 51 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.IsAny()) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 52 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 52 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Clone();\r\n");
            
            #line 53 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (!field.IsCsSimple() && field.IsMessage()) { 
            
            #line default
            #line hidden
            this.Write("    if (isDeep)\r\n        vm.");
            
            #line 55 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = vSharpStudio.vm.ViewModels.");
            
            #line 55 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".Clone(from.");
            
            #line 55 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(", isDeep);\r\n");
            
            #line 56 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 57 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 57 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 58 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } 
     } 
if (this.Doc.IsDefaultBase) {

            
            #line default
            #line hidden
            this.Write("    if (isNewGuid)\r\n        vm.SetNewGuid();\r\n");
            
            #line 64 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    return vm;\r\n}\r\npublic static void Update(");
            
            #line 67 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" to, ");
            
            #line 67 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" from, bool isDeep = true)\r\n{\r\n");
            
            #line 69 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    foreach (var field in message.Fields.InDeclarationOrder()) { 
        if (field.IsAny())
            continue;
        if (field.IsRepeated) { 
            
            #line default
            #line hidden
            
            #line 73 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (field.IsMessage()) { 
            
            #line default
            #line hidden
            this.Write("    if (isDeep)\r\n    {\r\n        foreach(var t in to.");
            
            #line 76 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".ToList())\r\n        {\r\n            bool isfound = false;\r\n            foreach(var" +
                    " tt in from.");
            
            #line 79 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                if (t == tt)\r\n                {\r\n              " +
                    "      isfound = true;\r\n                    vSharpStudio.vm.ViewModels.");
            
            #line 84 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".Update((");
            
            #line 84 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")t, (");
            
            #line 84 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")tt, isDeep);\r\n                    break;\r\n                }\r\n            }\r\n    " +
                    "        if (!isfound)\r\n                to.");
            
            #line 89 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Remove(t);\r\n        }\r\n        foreach(var tt in from.");
            
            #line 91 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            bool isfound = false;\r\n            foreach(var t in to." +
                    "");
            
            #line 94 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".ToList())\r\n            {\r\n                if (t == tt)\r\n                {\r\n     " +
                    "               isfound = true;\r\n                    break;\r\n                }\r\n " +
                    "           }\r\n            if (!isfound)\r\n            {\r\n                var p = " +
                    "new ");
            
            #line 104 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write("();\r\n                vSharpStudio.vm.ViewModels.");
            
            #line 105 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".Update(p, (");
            
            #line 105 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")tt, isDeep);\r\n                to.");
            
            #line 106 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(p);\r\n            }\r\n        }\r\n    }\r\n");
            
            #line 110 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        to.");
            
            #line 111 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Clear();\r\n        foreach(var tt in from.");
            
            #line 112 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            to.");
            
            #line 114 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(tt);\r\n        }\r\n");
            
            #line 116 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            
            #line 117 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name == "string_nullable") { 
            
            #line default
            #line hidden
            this.Write("    to.");
            
            #line 118 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 118 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 119 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name.EndsWith("_nullable")) { 
            
            #line default
            #line hidden
            this.Write("    to.");
            
            #line 120 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 120 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue ? from.");
            
            #line 120 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value : (");
            
            #line 120 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")null;\r\n");
            
            #line 121 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (!field.IsCsSimple() && field.IsMessage()) { 
            
            #line default
            #line hidden
            this.Write("    if (isDeep)\r\n        ");
            
            #line 123 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".Update(to.");
            
            #line 123 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(", from.");
            
            #line 123 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(", isDeep);\r\n");
            
            #line 124 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("    to.");
            
            #line 125 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = from.");
            
            #line 125 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 126 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } 
     } 
     
            
            #line default
            #line hidden
            this.Write("}\r\n#region IEditable\r\npublic override ");
            
            #line 131 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" Backup()\r\n{\r\n    bool isDeep = true;\r\n    OnBackupObjectStarting(ref isDeep);\r\n\t" +
                    "return ");
            
            #line 135 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Clone(this);\r\n}\r\npartial void OnBackupObjectStarting(ref bool isDeep);\r\npublic o" +
                    "verride void Restore(");
            
            #line 138 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" from)\r\n{\r\n    bool isDeep = true;\r\n    OnRestoreObjectStarting(ref isDeep);\r\n   " +
                    " ");
            
            #line 142 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Update(this, from, isDeep);\r\n}\r\npartial void OnRestoreObjectStarting(ref bool is" +
                    "Deep);\r\n#endregion IEditable\r\n// Conversion from \'");
            
            #line 146 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));
            
            #line default
            #line hidden
            this.Write("\' to \'");
            
            #line 146 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write("\'\r\npublic static ");
            
            #line 147 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" ConvertToVM(");
            
            #line 147 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.nameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 147 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));
            
            #line default
            #line hidden
            this.Write(" m, ");
            
            #line 147 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" vm = null)\r\n{\r\n    if (vm == null)\r\n        vm = new ");
            
            #line 150 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 151 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    foreach (var field in message.Fields.InDeclarationOrder()) { 
        if (field.IsAny())
            continue;
        if (field.IsRepeated) { 
            
            #line default
            #line hidden
            
            #line 155 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (field.IsCsSimple()) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 156 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new ObservableCollection<");
            
            #line 156 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(">();\r\n    foreach(var t in m.");
            
            #line 157 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        vm.");
            
            #line 159 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(t);\r\n    }\r\n");
            
            #line 161 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else if (!JsonDoc.Files[root.Name].Messages[field.MessageType.Name].IsDefaultBase) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 162 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new ObservableCollection<");
            
            #line 162 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(">();\r\n    foreach(var t in m.");
            
            #line 163 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        var tvm = vSharpStudio.vm.ViewModels.");
            
            #line 165 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".ConvertToVM(t);\r\n");
            
            #line 166 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (JsonDoc.Files[root.Name].Messages[field.MessageType.Name].IsDefaultBase) { 
            
            #line default
            #line hidden
            this.Write("        tvm.Parent = vm;\r\n");
            
            #line 168 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        vm.");
            
            #line 169 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(tvm);\r\n    }\r\n");
            
            #line 171 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 172 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new SortedObservableCollection<");
            
            #line 172 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(">();\r\n    foreach(var t in m.");
            
            #line 173 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        var tvm = vSharpStudio.vm.ViewModels.");
            
            #line 175 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".ConvertToVM(t);\r\n");
            
            #line 176 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (JsonDoc.Files[root.Name].Messages[field.MessageType.Name].IsDefaultBase) { 
            
            #line default
            #line hidden
            this.Write("        tvm.Parent = vm;\r\n");
            
            #line 178 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        vm.");
            
            #line 179 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(tvm);\r\n    }\r\n");
            
            #line 181 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            
            #line 182 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name == "string_nullable") { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 183 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = m.");
            
            #line 183 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue ? m.");
            
            #line 183 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value : \"\";\r\n");
            
            #line 184 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name.EndsWith("_nullable")) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 185 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = m.");
            
            #line 185 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue ? m.");
            
            #line 185 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value : (");
            
            #line 185 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")null;\r\n");
            
            #line 186 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (!field.IsCsSimple() && field.IsMessage()) { 
            
            #line default
            #line hidden
            this.Write("    vSharpStudio.vm.ViewModels.");
            
            #line 187 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".ConvertToVM(m.");
            
            #line 187 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(", vm.");
            
            #line 187 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 188 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsBytes()) { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 189 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = m.");
            
            #line 189 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".ToByteArray();\r\n");
            
            #line 190 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.FieldType == Google.Protobuf.Reflection.FieldType.Enum) {
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 191 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 191 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")m.");
            
            #line 191 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 192 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("    vm.");
            
            #line 193 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = m.");
            
            #line 193 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 194 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } 
     } 
     
            
            #line default
            #line hidden
            
            #line 197 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (this.Doc.IsDefaultBase) { 
            
            #line default
            #line hidden
            this.Write("    vm.OnInitFromDto();\r\n");
            
            #line 199 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    return vm;\r\n}\r\n// Conversion from \'");
            
            #line 202 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write("\' to \'");
            
            #line 202 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));
            
            #line default
            #line hidden
            this.Write("\'\r\npublic static ");
            
            #line 203 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.nameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 203 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));
            
            #line default
            #line hidden
            this.Write(" ConvertToProto(");
            
            #line 203 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" vm)\r\n{\r\n    ");
            
            #line 205 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.nameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 205 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));
            
            #line default
            #line hidden
            this.Write(" m = new ");
            
            #line 205 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.nameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 205 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(message.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 206 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
    foreach (var field in message.Fields.InDeclarationOrder()) { 
        if (field.IsRepeated) { 
            
            #line default
            #line hidden
            this.Write("    foreach(var t in vm.");
            
            #line 208 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 209 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 if (field.IsCsSimple()) { 
            
            #line default
            #line hidden
            this.Write("        m.");
            
            #line 210 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(t);\r\n");
            
            #line 211 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        m.");
            
            #line 212 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Add(vSharpStudio.vm.ViewModels.");
            
            #line 212 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".ConvertToProto((");
            
            #line 212 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(")t));\r\n");
            
            #line 213 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
 } 
            
            #line default
            #line hidden
            
            #line 214 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name == "string_nullable") { 
            
            #line default
            #line hidden
            this.Write("    m.");
            
            #line 215 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value = string.IsNullOrEmpty(vm.");
            
            #line 215 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(") ? \"\" : vm.");
            
            #line 215 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n    m.");
            
            #line 216 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue = !string.IsNullOrEmpty(vm.");
            
            #line 216 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 217 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsMessage() && field.MessageType.Name.EndsWith("_nullable")) { 
            
            #line default
            #line hidden
            this.Write("    m.");
            
            #line 218 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 218 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.nameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 218 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.MessageType.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n    m.");
            
            #line 219 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue = vm.");
            
            #line 219 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue;\r\n    if (vm.");
            
            #line 220 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".HasValue)\r\n        m.");
            
            #line 221 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value = vm.");
            
            #line 221 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(".Value;\r\n");
            
            #line 222 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (!field.IsCsSimple() && field.IsMessage() && !field.IsAny()) { 
            
            #line default
            #line hidden
            this.Write("    m.");
            
            #line 223 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = vSharpStudio.vm.ViewModels.");
            
            #line 223 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.ToTypeCs()));
            
            #line default
            #line hidden
            this.Write(".ConvertToProto(vm.");
            
            #line 223 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 224 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.IsBytes()) { 
            
            #line default
            #line hidden
            this.Write("    m.");
            
            #line 225 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = ByteString.CopyFrom(vm.");
            
            #line 225 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 226 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else if (field.FieldType == Google.Protobuf.Reflection.FieldType.Enum) {
            
            #line default
            #line hidden
            this.Write("    m.");
            
            #line 227 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 227 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.nameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 227 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.EnumType.Name));
            
            #line default
            #line hidden
            this.Write(")vm.");
            
            #line 227 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 228 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("    m.");
            
            #line 229 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(" = vm.");
            
            #line 229 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToNameCs()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 230 "C:\dev\vsharpstudio\generators\GenFromProto\Clone.tt"
      } 
     } 
     
            
            #line default
            #line hidden
            this.Write("    return m;\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class CloneBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
