<Project Sdk="Microsoft.NET.Sdk">
  <!--https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained-->
  <PropertyGroup>
    <!--https://learn.microsoft.com/en-us/dotnet/core/rid-catalog-->
    <!--<RuntimeIdentifier>win-x64</RuntimeIdentifier>-->
    <TargetFrameworkVariation>windows</TargetFrameworkVariation>
    <OutputType>WinExe</OutputType>
    <ProjectTypeGuids>{60dc8134-eba5-43b8-bcc9-bb4bc16c2548};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <AssemblyTitle>vSharpStudio</AssemblyTitle>
    <Product>vSharpStudio</Product>
    <Copyright>Copyright ©  2019</Copyright>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <!--<TargetFramework>net9.0-windows</TargetFramework>-->
    <!--<TargetFramework>net9.0-windows7.0</TargetFramework>-->
  </PropertyGroup>
  <Import Project="..\Solution.targets" />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="icons\SettingsFile_16x.png" />
    <None Remove="icons\Settings_16x.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\vSharpStudio.vm\GlobalUsing.cs" Link="GlobalUsing.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Controls\vButton.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Controls\CollectionFromCollection.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\common\wpf\vSharpStudio.std\vSharpStudio.std.csproj" />
    <ProjectReference Include="..\common\wpf\vSharpStudio.wpf\vSharpStudio.wpf.csproj" />
    <ProjectReference Include="..\ext\UndoFramework\UndoFramework.csproj" />
    <ProjectReference Include="..\submodules\wpftoolkit\ExtendedWPFToolkitSolution\Src\Xceed.Wpf.Toolkit\Xceed.Wpf.Toolkit.csproj" />
    <ProjectReference Include="..\vSharpStudio.vm\vSharpStudio.vm.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices.MVVM" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.3.0" />

    <PackageReference Include="Microsoft.Build.Framework" Version="18.6.3" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.6.3" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.6.3" />

    <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CompareNETObjects" Version="4.84.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <!--<PackageReference Include="GitVersionTask" Version="5.3.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>-->
    <PackageReference Include="WpfScreenHelper" Version="2.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="icons\SettingsFile_16x.png" />
    <Resource Include="icons\Settings_16x.png" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="vSharpStudio Debug.licence.rtf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Controls\CollectionFromCollection.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
</Project>